name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    name: Deploying everything to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH key and add remote server to known_hosts
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.60.253.180 >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        run: |
          ssh -t -i ~/ssh_key ubuntu@13.60.253.180 << 'EOF'
            cd Devops-MonoRepo-Test && git pull
            pnpm install
            pnpm run build
            pm2 restart 3
            pm2 restart 0
            pm2 restart 1
          EOF
  